apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-music-adam
  labels:
    app: react-music-adam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-music-adam
  template:
    metadata:
      labels:
        app: react-music-adam
    spec:
      containers:
        - name: react-music-adam
          image: docker.io/hauze/react-music-adam:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: react-music-adam
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
