import { v4 as uuidv4 } from "uuid";
import aftergoldImg from "./images/aftergold_big_wild.jpg";

function chillHop() {
  return [
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Aftergold.mp3`,
      cover: aftergoldImg,
      time: "03:50",
      name: "Aftergold",
      artist: "Big Wild",
      color: ["#404035", "#7c7b66"],
      active: true,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Angst.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/angst_inzo.jpg`,
      time: "03:17",
      name: "Angst",
      artist: "Inzo",
      color: ["#3d0159", "#f72ba6"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Overthinker.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/overthinker_inzo.jpg`,
      time: "04:34",
      name: "Overthinker",
      artist: "Inzo",
      color: ["#e40098", "#e58eeb"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Fairy_Tale.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/fairy_tale_ekali.jpg`,
      time: "04:16",
      name: "Fairly Tale",
      artist: "Ekali",
      color: ["#d8031d", "#1249ad"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Griztronics.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/griztronics.jpg`,
      time: "03:19",
      name: "Griztronics",
      artist: "Subtronics",
      color: ["#10fbc1", "#fc8f52"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Hard_to_say_goodbye.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/hard_to_say_goodbye_ekali.jpg`,
      time: "03:17",
      name: "Hard to Say Goodbye",
      artist: "Ekali",
      color: ["#325c86", "#e26854"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Last_to_leave.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/last_to_leave_louis_the_child.jpg`,
      time: "03:00",
      name: "Last to Leave",
      artist: "Louis The Child",
      color: ["#fad521", "#0c5892"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Late_night.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/late_night_odesza.jpg`,
      time: "03:48",
      name: "Late Night",
      artist: "Odesza",
      color: ["#5e84c4", "#223872"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Losing_it.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/losing_it_fisher.jpg`,
      time: "06:41",
      name: "Losing It",
      artist: "Fisher",
      color: ["#ef7311", "#6a2a12"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Magnets.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/magnets_zeds_dead.jpg`,
      time: "04:19",
      name: "Magnets",
      artist: "Zeds Dead",
      color: ["#0a499f", "#e81667"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Only_now.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/only_now_seven_lions.jpg`,
      time: "03:31",
      name: "Only Now",
      artist: "Seven Lions",
      color: ["#447677", "#c6d3c9"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Remember.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/remember.jpg`,
      time: "05:14",
      name: "Remember",
      artist: "Seven Lions",
      color: ["#678da0", "#766e63"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: `${process.env.PUBLIC_URL}/music/Promises.mp3`,
      cover: `${process.env.PUBLIC_URL}/images/promises_nero.jpg`,
      time: "04:28",
      name: "Promises",
      artist: "Skrillex",
      color: ["#232f7a", "#fbfbfb"],
    },
  ];
}

export default chillHop;
