import { v4 as uuidv4 } from "uuid";
function chillHop() {
  return [
    {
      id: uuidv4(),
      audio: "/src/music/Aftergold.mp3",
      cover: "/src/images/aftergold_big_wild.jpg",
      time: "03:50",
      name: "Aftergold",
      artist: "Big Wild",
      color: ["#205950", "#2ab3bf"],
      active: true,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Angst.mp3",
      cover: "/src/images/angst_inzo.jpg",
      time: "03:17",
      name: "Angst",
      artist: "Inzo",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Overthinker.mp3",
      cover: "/src/images/overthinker_inzo.jpg",
      time: "04:34",
      name: "Overthinker",
      artist: "Inzo",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Fairy_Tale.mp3",
      cover: "/src/images/fairy_tale_ekali.jpg",
      time: "04:16",
      name: "Fairly Tale",
      artist: "Ekali",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Griztronics.mp3",
      cover: "/src/images/griztronics.jpg",
      time: "03:19",
      name: "Griztronics",
      artist: "Subtronics",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Hard_to_say_goodbye.mp3",
      cover: "/src/images/hard_to_say_goodbye_ekali.jpg",
      time: "03:17",
      name: "Hard to Say Goodbye",
      artist: "Ekali",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Last_to_leave.mp3",
      cover: "/src/images/last_to_leave_louis_the_child.jpg",
      time: "03:00",
      name: "Last to Leave",
      artist: "Louis The Child",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Late_night.mp3",
      cover: "/src/images/late_night_odesza.jpg",
      time: "03:48",
      name: "Late Night",
      artist: "Odesza",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Losing_it.mp3",
      cover: "/src/images/losing_it_fisher.jpg",
      time: "06:41",
      name: "Losing It",
      artist: "Fisher",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Magnets.mp3",
      cover: "/src/images/magnets_zeds_dead.jpg",
      time: "04:19",
      name: "Magnets",
      artist: "Zeds Dead",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Only_now.mp3",
      cover: "/src/images/only_now_seven_lions.jpg",
      time: "03:31",
      name: "Only Now",
      artist: "Seven Lions",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Remember.mp3",
      cover: "/src/images/remember.jpg",
      time: "05:14",
      name: "Remember",
      artist: "Seven Lions",
      color: ["#205950", "#2ab3bf"],
      active: false,
    },
    {
      id: uuidv4(),
      audio: "/src/music/Promises.mp3",
      cover: "/src/images/promises_nero.jpg",
      time: "04:28",
      name: "Promises",
      artist: "Skrillex",
      color: ["#205950", "#2ab3bf"],
    },
  ];
}

export default chillHop;
